name: Generar Reporte en Google Sheets

on:
  workflow_dispatch:
  
 # Lista de tareas programadas (cron jobs)
schedule:
  # Lunes a Viernes en horarios específicos.
  - cron: '25 10,11,12,13,14,15,16,17,20 * * 1-5'

  # Sábados en horarios específicos.
  - cron: '25 12 * * 6'
  - cron: '25 18 * * 6'
  - cron: '45 20 * * 6'

  # Domingos a las 20:25.
  - cron: '25 20 * * 0'

jobs:
  generar-reporte:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Report Generation Script
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          GOOGLE_SHEETS_SHARE_EMAIL: ${{ secrets.GOOGLE_SHEETS_SHARE_EMAIL }}
        run: python script_reporte_sheets.py
