name: Sincronizar Pedidos de WooCommerce

on:
  workflow_dispatch:
  schedule:
    # Se ejecuta cada 10 minutos, todos los días.
    - cron: '*/10 * * * *'

jobs:
  sincronizar:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger WooCommerce Sync API
        env:
          REGISTRATION_API_KEY: ${{ secrets.REGISTRATION_API_KEY }}
          HOST_URL: https://registroimeimultibanda.cl
        run: |
          curl -X POST "$HOST_URL/api/sync-woocommerce/" \
            -H "Authorization: Bearer $REGISTRATION_API_KEY" \
            -H "Content-Type: application/json"
