
name: Sincronizar Pedidos de WooCommerce

on:
  workflow_dispatch:
  schedule:
    # Se ejecuta cada 15 minutos, todos los días.
    - cron: '*/15 * * * *'

jobs:
  sincronizar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run WooCommerce Sync Script
        env:
          REGISTRATION_API_KEY: ${{ secrets.REGISTRATION_API_KEY }}
          HOST_URL: https://registroimeimultibanda.cl
        run: python sync_woocommerce.py
