name: Verificador Automatico de IMEI (GSHEET)

on:
  # Para que puedas seguir ejecutándolo manualmente
  workflow_dispatch:
  
  # Para ejecutarlo en el horario programado
  schedule:
    # Se ejecuta cada 15 minutos, todos los días.
    - cron: '*/15 * * * *'


jobs:
  verificar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run IMEI Check Script
        env:
          GSPREAD_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          GSPREAD_SHEET_NAME: ${{ secrets.GSPREAD_SHEET_NAME }}
        run: python script.py
